backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
waybar.template = 'waybar-colors.css'
waybar.target = '~/.config/waybar/colors.css'
dunst.template = 'dunst-colors.conf'
dunst.target = '~/.config/dunst/dunstrc.d/color.conf'
hyprland.template = 'hyprland-colors.lua'
hyprland.target = '~/.config/hypr/sources/colors.lua'
kitty.template = 'kitty-colors.conf'
kitty.target = '~/.config/kitty/colors.conf'
rofi.template = 'rofi-colors.rasi'
rofi.target = '~/.config/rofi/colors.rasi'
wlogout.template = 'wlogout-colors.css'
wlogout.target = '~/.config/wlogout/colors.css'

