[global]
frame_color = "#24283b80" 
separator_color = frame
highlight = "#24283b20"

[urgency_low]
background = "#414868"
foreground - "#a9b1d6"
default_icon = dialog-information 

[urgency_normal]
background = "#414868"
foreground - "#a9b1d6"
default_icon = dialog-information

[urgency_critical]
background = "#414868"
foreground = "#a9b1d6"
frame_color = "#e0af68"
default_icon = dialog-warning
