[global]
frame_color = "#8caaee80"
separator_color = frame
highlight = "#8caaee20"

[urgency_low]
background = "#303446"
foreground = "#c6d0f5"
default_icon = dialog-information

[urgency_normal]
background = "#303446"
foreground = "#c6d0f5"
default_icon = dialog-information

[urgency_critical]
background = "#303446"
foreground = "#c6d0f5"
frame_color = "#ef9f76"
default_icon = dialog-warning
