general {
    ignore_empty_input = true
  }

background {
    path = ~/Pictures/wallpapers/guts.png
    blur_passes = 3
    blur_size = 7
    vibrancy = 0.1696
}
input-field{
    size = 20% 5%
    position = 0, 20
  }
