pragma Singleton
import QtQuick

QtObject {
  readonly property string lowBattery: "󰁺"
  readonly property string midBattery: "󰁼"
  readonly property string highBattery: "󰁾"
  readonly property string almostFullBattery: "󰂁"
  readonly property string fullBattery: "󰁹"
  readonly property string lowChargingBattery: "󰢜"
  readonly property string midChargingBattery: "󰂇"
  readonly property string highChargingBattery: "󰢝"
  readonly property string almostFullChargingBattery: "󰂊"
  readonly property string fullChargingBattery: "󰂅"
  readonly property string lowVolume: "󰕿"
  readonly property string midVolume: "󰖀"
  readonly property string highVolume: "󰕾"
  readonly property string bluetoothVolume: "󰥰"
  readonly property string muted: "󰝟"
  readonly property string lowBrightness: "󰃞"
  readonly property string midBrightness: "󰃟"
  readonly property string highBrightness: "󰃠"
  readonly property string weakWifi: "󰤟"
  readonly property string midWifi: "󰤢"
  readonly property string highWifi: "󰤥"
  readonly property string strongWifi: "󰤨"
  readonly property string disconnectedWifi: "󰤭"
  readonly property string airplaneModeOn: "󰀝"
  readonly property string airplaneModeOff: "󰀞"
  readonly property string bluetooth: "󰂯"
  readonly property string noBluetooth: "󰂲"
  readonly property string connectedBluetooth: "󰂱"
  readonly property string power: ""
  readonly property string mediaPlayer: "󰎇"
  readonly property string arrowLeft: ""
  readonly property string lock: ""
  readonly property string logout: ""
  readonly property string reboot: ""
  readonly property string dodi: "do"
}
