[global]
frame_color = "{{background}}80" 
separator_color = frame
highlight = "{{background}}20"

[urgency_low]
background = "{{color0}}"
foreground = "{{foreground}}"
default_icon = dialog-information

[urgency_normal
background = "{{color0}}"
foreground = "{{foreground}}"
default_icon = dialog-information

[urgency-critical]
background = "{{color0}}"
foreground = "{{foreground}}"
frame_color = "{{color3}}" 
default_icon = dialog-information
